force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <label>Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TestDelForecast.cls
@isTest
public class TestDelForecast {
  @isTest
  static void TestDeleteForecastsWithEqualNames() {
    Weather_Setting__c setting = Weather_Setting__c.getInstance();
    City__c city = new City__c();
    insert city;
    List<Forecast__c> forecastsFirst = TestDataFactory.createForecasts(
      1,
      'Paris',
      45
    );
    List<Forecast__c> forecastsSecond = TestDataFactory.createForecasts(
      2,
      'jhhvkg',
      -50
    );
    Test.startTest();
    try {
      List<Forecast__c> accts = WeatherController.refreshWeather('Paris');
    } catch (exception e) {
    }
    Test.stopTest();
  }
}