force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <label>Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Time__c.field-meta.xml
<CustomField>
    <fullName>Time__c</fullName>
    <label>Time</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Weather_message__c.field-meta.xml
<CustomField>
    <fullName>Weather_message__c</fullName>
    <label>Weather message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/Circle.cls
public with sharing class Circle {
  public List<Forecast__c> createCircle(Map<String, Object> responseMap) {
    CityChild cityChild = new CityChild();
    List<Forecast__c> objList = new List<Forecast__c>();
    City__c cityObj = cityChild.getChild(responseBody);

    for (Integer i = 0; i < 40; i++) {
      Forecast__c forecast = new Forecast__c();

      List<Object> ListGlobal = (List<Object>) responseMap.get('list');
      Map<String, Object> weatherInfoGlobal = (Map<String, Object>) ListGlobal[
        i
      ];
      Map<String, Object> mainMap = (Map<String, Object>) weatherInfoGlobal.get(
        'main'
      );
      Double temperature = Double.valueOf(mainMap.get('temp'));
      List<Object> WeatherList = (List<Object>) weatherInfoGlobal.get(
        'weather'
      );
      Map<String, Object> weatherInfo = (Map<String, Object>) WeatherList[0];
      String weatherDesc = String.valueOf(weatherInfo.get('description'));
      String dateTimeResponce = String.valueOf(weatherInfoGlobal.get('dt_txt'));

      String year = dateTimeResponce.substring(0, 4);
      String month = dateTimeResponce.substring(5, 7);
      String day = dateTimeResponce.substring(8, 10);
      String hour = dateTimeResponce.substring(11, 13);
      String minute = dateTimeResponce.substring(14, 16);
      String second = dateTimeResponce.substring(17, 19);
      String timeString = dateTimeResponce.substring(11);

      DateTime thisDate = DateTime.newInstanceGmt(
        integer.valueOf(year),
        integer.valueOf(month),
        integer.valueOf(day),
        integer.valueOf(hour),
        integer.valueOf(minute),
        integer.valueOf(second)
      );

      String[] strTimeSplit = timeString.split(':');
      Time showTime = Time.newInstance(
        Integer.valueOf(strTimeSplit[0]),
        Integer.valueOf(strTimeSplit[1]),
        0,
        0
      );

      forecast.Name = cityFromJson; //cityFromJson +' '+ String.valueOfGmt(thisDate);
      forecast.City__c = cityChild.id;
      forecast.Temperature__c = temperature;
      forecast.Weather_message__c = 'goodi';
      forecast.Date__c = thisDate;
      forecast.Time__c = showTime;
      objList.add(forecast);
    }

    return objectList;
  }
}