force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/City__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CityChild.cls
public with sharing class CityChild {
  public City__c getChild(String responseBody) {
    Map<String, Object> responseMap = (Map<String, Object>) JSON.deserializeUntyped(
      responseBody
    );

    City__c cityChild = new City__c();
    Map<String, Object> cityMap = (Map<String, Object>) responseMap.get('city');
    String cityFromJson = String.valueOf(cityMap.get('name'));
    String countryFromJson = String.valueOf(cityMap.get('country'));
    cityChild.Country__c = countryFromJson;
    cityChild.Name = cityFromJson;
    upsert cityChild;
    return cityChild;
  }
}