force-app/main/default/objects/City__c/City__c.object-meta.xml
<CustomObject>
    <label>City</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/Forecast__c.object-meta.xml
<CustomObject>
    <label>Forecast</label>
    <nameField>
        <label>Forecast Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Forecasts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Forecast__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <referenceTo>City__c</referenceTo>
    <relationshipLabel>Forecasts</relationshipLabel>
    <relationshipName>Forecasts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Forecast__c/fields/Weather_message__c.field-meta.xml
<CustomField>
    <fullName>Weather_message__c</fullName>
    <label>Weather message</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
  public static List<Forecast__c> createForecasts(
    Integer numFrcsts,
    String name,
    Integer temperature
  ) {
    Weather_Setting__c setting = Weather_Setting__c.getInstance();
    List<Forecast__c> forecasts = new List<Forecast__c>();
    City__c city = new City__c();
    insert city;
    for (Integer i = 0; i < numFrcsts; i++) {
      Forecast__c a = new Forecast__c(
        Name = name + i,
        City__c = city.Id,
        Weather_Message__c = 'foo',
        Temperature__c = temperature
      );
      forecasts.add(a);
    }
    insert forecasts;
    forecasts = [
      SELECT Name, City__c, Weather_Message__c, Temperature__c
      FROM Forecast__c
      WHERE Id IN :forecasts
    ];
    return forecasts;
  }
}